FROM python:3.10-slim

WORKDIR /app

COPY requirements.inference.txt .

RUN pip install --no-cache-dir -r requirements.inference.txt

COPY . .

# très important :
COPY mlruns ./mlruns

CMD ["uvicorn", "api.apimain:app", "--host", "0.0.0.0", "--port", "8000"]
