stages:
  preprocessing:
    cmd: python src/preprocessing.py
    deps:
    - data/raw/creditcard.csv
    - src/preprocessing.py
    outs:
    - data/processed/cleaned.csv

  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - data/processed/cleaned.csv
    outs:
    - models/model.pkl
    metrics:
    - metrics/metrics.json:   
        cache: false
